// Curated list of 250 memorable, clean English words for passphrase generation.
export const WORDLIST = [
  "actor", "agent", "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow",
  "alone", "along", "alter", "among", "anger", "angle", "angry", "apart", "apple", "apron",
  "arena", "argue", "arise", "arrow", "aside", "asset", "atlas", "audio", "audit", "avoid",
  "award", "aware", "awful", "bacon", "badge", "baker", "basic", "basis", "beach", "beard",
  "beast", "begin", "below", "bench", "berry", "bible", "birth", "black", "blade", "blame",
  "blank", "blast", "blend", "blind", "blink", "block", "blood", "board", "boast", "bonus",
  "boost", "bound", "brain", "brand", "brass", "brave", "bread", "break", "brick", "bride",
  "brief", "bright", "broad", "brown", "brush", "buyer", "cabin", "cable", "camel", "camera",
  "candy", "canoe", "cargo", "carve", "cater", "cause", "chain", "chair", "chalk", "champ",
  "chaos", "charm", "chart", "chase", "cheap", "check", "cheek", "cheer", "chess", "chest",
  "chief", "child", "chime", "china", "choir", "choke", "chord", "chunk", "cider", "cigar",
  "circus", "civet", "claim", "clamp", "clash", "clasp", "class", "clean", "clear", "cleft",
  "clerk", "click", "cliff", "climb", "cling", "cloak", "clock", "clone", "close", "cloth",
  "cloud", "clove", "clown", "coach", "coast", "cobra", "cocoa", "coffee", "colic", "colt",
  "comet", "comic", "comma", "conch", "conic", "coral", "couch", "cough", "count", "court",
  "covey", "coyote", "crack", "craft", "crane", "crank", "crash", "crate", "crater", "crawl",
  "craze", "crazy", "cream", "creed", "creek", "creep", "crest", "cricket", "cried", "crier",
  "crime", "crimp", "crisp", "crook", "crop", "cross", "crowd", "crown", "crude", "cruel",
  "crumb", "crush", "crust", "crypt", "cubit", "cult", "cupid", "curry", "purse", "cycle",
  "cynic", "daily", "dairy", "daisy", "dance", "dandy", "datum", "daunt", "dawn", "dazzle",
  "deal", "death", "decor", "decoy", "delay", "delta", "demon", "denim", "dense", "depot",
  "depth", "derby", "desert", "desk", "devil", "diary", "digit", "dime", "diner", "dingo",
  "dinky", "dirty", "disco", "ditch", "diver", "dizzy", "dock", "dodge", "dogma", "dolly",
  "donor", "donut", "doom", "door", "doubt", "dough", "douse", "dove", "down", "doze",
  "draft", "drag", "drain", "drake", "drama", "drank", "drape", "drawl", "dread", "dream",
];
